3

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,40 +1,46 @@
 version: 2.1
 
+executors:
+  node-executor:
+    docker:
+      - image: cimg/node:20.11
+    working_directory: ~/project
+
 jobs:
   ui-tests:
-    docker:
-      - image: cimg/node:18.17
+    executor: node-executor
     steps:
       - checkout
       - run:
-          name: Install all UI dependencies
-          command: |
-            cd AutomationTask/UI_Task/Task1 && npm install
-            cd ../Task2 && npm install
-            cd ../Task3 && npm install
+          name: Install dependencies
+          command: npm install
       - run:
-          name: Run all UI Nightwatch tests
-          command: npx nightwatch AutomationTask/UI_Task/**/test/*.js
+          name: Run Nightwatch UI Tests
+          command: |
+            # تأكد إن ملف الـ config موجود
+            if [ ! -f AutomationTask/UI_Task/nightwatch.conf.js ]; then
+              echo "❌ Nightwatch config file not found!"
+              exit 1
+            fi
+
+            # شغل الاختبارات من المسار الصحيح
+            npx nightwatch --config AutomationTask/UI_Task/nightwatch.conf.js "AutomationTask/UI_Task/**/test/*.js"
 
   api-tests:
-    docker:
-      - image: cimg/node:18.17
+    executor: node-executor
     steps:
       - checkout
       - run:
-          name: Install API dependencies
-          command: |
-            cd AutomationTask/API_Task
-            npm install
+          name: Install dependencies
+          command: npm install
       - run:
-          name: Run all API tests
-          command: npx jest AutomationTask/API_Task/tests/*.js
+          name: Run API Tests
+          command: |
+            npx playwright test --config=AutomationTask/API_Task/playwright.config.js
 
 workflows:
   version: 2
-  test-all:
+  test_all:
     jobs:
       - ui-tests
-      - api-tests:
-          requires:
-            - ui-tests
+      - api-tests
